# docker compose version which is currently 4.21
version: "4.21"

# services : is a list of our container
services:
  mongodb:
    image: "mongo"
    container_name: mongodb
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - logs:/client/logs
      - ./client:/client
      - /client/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api
    networks:
      - yt-sharing

  api:
    build: /back-end
    ports:
      - "5000:5000"
    working_dir: /back-end
    volumes:
      - logs:/back-end/logs
      - ./api:/api
      - /api/node_modules
    env_file:
      - ./back-end/.env
    depends_on: 
      - mongodb
    networks:
      - yt-sharing

networks:
  yt-sharing:
    driver: bridge

volumes:
  data:
    driver: local
  logs:
