# docker compose version which is currently 4.21
version: "4.21"

# services : is a list of our container
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    networks:
      - yt-sharing

  api:
    build:
      context: ./back-end
    container_name: yt-api
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://mongodb:27017
      DB_NAME: yt-sharing
      NAME: HienPhan
      JWT_SECRET: secret
    volumes:
      - logs:/back-end/logs
      - ./api:/api
      - /api/node_modules
    depends_on: 
      - mongodb
    networks:
      - yt-sharing

  client:
    build:
      context: ./client
    container_name: yt-client
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5000
    # volumes:
    #   - logs:/client/logs
    #   - ./client:/client
    #   - /client/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api
    networks:
      - yt-sharing

networks:
  yt-sharing:
    driver: bridge

volumes:
  data:
    driver: local
  logs:
