# docker compose version which is currently 4.21
version: "4.21"

# services : is a list of our container
services:
  client:
    image: webapp-client
    restart: always
    ports:
      - "3000:3000"
    working_dir: /client
    volumes: 
      - ./client:/client
      - /client/node_modules
    entrypoint: ["npm", "start"]
    links:
      - api
    networks:
      - webappnetwork

  api:
    image: webapp-api
    restart: always
    ports:
      - "5000:5000"
    volumes: 
      - ./api:/api
      - /api/node_modules
    depends_on: 
      - mongodb
    networks:
      - webappnetwork

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod -noauth --smallfiles
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge